name: dart_desktop_dev
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  dart_common_dev:
    path: ../dart_common_dev
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  library_architecture_mvvm_modify: ^6.1.2
  meta: ^1.15.0
  intl: ^0.20.2
  responsive_framework: ^1.5.1
  window_manager: ^0.3.9
  system_tray: ^2.0.3
  go_router: ^15.1.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.14

flutter:
  assets:
    - assets/icons/desktop/app_icon.ico
    - assets/icons/large_desktop/app_icon.ico
    - assets/icons/large_tablet/app_icon.ico
    - assets/icons/mobile/app_icon.ico
    - assets/icons/tablet/app_icon.ico
    - assets/icons/tv/app_icon.ico
    - assets/icons/app_icon.ico
    - assets/images/desktop/app_icon.png
    - assets/images/large_desktop/app_icon.png
    - assets/images/large_tablet/app_icon.png
    - assets/images/mobile/app_icon.png
    - assets/images/tablet/app_icon.png
    - assets/images/tv/app_icon.png
    - assets/images/app_icon.png
    - assets/images/dev.png
    ## Don't forget to comment out the this line so that the tests in GitHub Action are successful.
    ##- assets/.env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_18pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_24pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_28pt_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/inter_18pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_24pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_28pt_medium.ttf
          weight: 500
        - asset: assets/fonts/inter_18pt_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_24pt_regular.ttf
          weight: 400
        - asset: assets/fonts/inter_28pt_regular.ttf
          weight: 400
  uses-material-design: true
  generate: true