#!/bin/bash
cat <<EOF > dart_web_boilerplate/app/assets/.env
API_KEY=${API_KEY}
EOF
cat <<EOF > typescript_api_boilerplate/.env
JWT_SECRET_KEY=${JWT_SECRET_KEY}
DB_DEPENDENCY_NAME=${DB_DEPENDENCY_NAME}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
ADMINER_PORT=${ADMINER_PORT}
APP_PORT=${APP_PORT}
NGINX_PORT=${NGINX_PORT}
EOF
echo ".env file generated successfully."
