version: "3"

env:
  app_directory: ./app

tasks:
  npm:download:
    dir: "{{.app_directory}}"
    cmds:
      - npm run download
  npm:build:
    dir: "{{.app_directory}}"
    cmds:
      - npm run build
  npm:test:
    dir: "{{.app_directory}}"
    cmds:
      - npm run test
  npm:dev:run:
    dir: "{{.app_directory}}"
    cmds:
      - npm run server:dev
  npm:prod:run:
    dir: "{{.app_directory}}"
    cmds:
      - npm run server:prod
  docker:run:
    cmds:
      - docker-compose down
      - docker-compose up --build
  docker:stop:
    cmds:
      - docker-compose down