name: dart_desktop_dev-building_executable_files
run-name: ${{ github.actor }} - dart_desktop_dev-building_executable_files
on:
  workflow_dispatch:
env:
  flutter_channel: stable
  flutter_channel_w_arm64: master
  working_directory: dart_desktop_dev
  app_name: dev
jobs:
  build_linux_x64:
    runs-on: ubuntu-latest
    steps:
      - run: echo "created_at=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt install libayatana-appindicator3-dev
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter build linux --target-platform=linux-x64
        working-directory: ${{ env.working_directory }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.created_at }}_${{ env.app_name }}_x64
          path: ${{ env.working_directory }}/build/linux/x64/release/bundle/
  build_linux_arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: echo "created_at=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libglib2.0-dev libgdk-pixbuf2.0-dev
          sudo apt install libayatana-appindicator3-dev
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel_w_arm64 }}
      - run: flutter build linux --target-platform=linux-arm64
        working-directory: ${{ env.working_directory }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.created_at }}_${{ env.app_name }}_arm64
          path: ${{ env.working_directory }}/build/linux/arm64/release/bundle/
  build_windows:
    runs-on: windows-latest
    steps:
      - run: |
          $date = Get-Date -Format "yyyy_MM_dd_HH_mm"
          echo "created_at=$date" >> $env:GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter build windows
        working-directory: ${{ env.working_directory }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.created_at }}_${{ env.app_name }}_exe
          path: ${{ env.working_directory }}\build\windows\x64\runner\Release\
  build_macos:
    runs-on: macos-latest
    steps:
      - run: echo "created_at=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter build macos
        working-directory: ${{ env.working_directory }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.created_at }}_${{ env.app_name }}_app
          path: ${{ env.working_directory }}/build/macos/Build/Products/Release/
