name: dart_mobile_dev-running_unit_tests
run-name: ${{ github.actor }} - dart_mobile_dev-running_unit_tests
on:
  push:
    branches:
      - sl8s
  workflow_dispatch:
env:
  flutter_channel: stable
  working_directory: dart_mobile_dev
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter test
        working-directory: ${{ env.working_directory }}