name: kotlin_android_dev-building_executable_files
run-name: ${{ github.actor }} - kotlin_android_dev-building_executable_files
on:
  workflow_dispatch:
env:
  java_distribution: "zulu"
  java_version: "17"
  java_cache: "gradle"
  working_directory: kotlin_android_dev
  app_name: dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "created_at=$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.java_distribution }}
          java-version: ${{ env.java_version }}
          cache: ${{ env.java_cache }}
      - run: ./gradlew build
        working-directory: ${{ env.working_directory }}
      - run: ./gradlew assemble
        working-directory: ${{ env.working_directory }}
      - run: ./gradlew bundleRelease
        working-directory: ${{ env.working_directory }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.created_at }}_${{ env.app_name }}_apk
          path: ${{ env.working_directory }}/app/build/outputs/apk/release/
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.created_at }}_${{ env.app_name }}_aab
          path: ${{ env.working_directory }}/app/build/outputs/bundle/release/