name: kotlin_android_dev-running_unit_tests
run-name: ${{ github.actor }} - kotlin_android_dev-running_unit_tests
on:
  push:
    branches:
      - sl8s
  workflow_dispatch:
env:
  java_distribution: "zulu"
  java_version: "17"
  java_cache: "gradle"
  working_directory: kotlin_android_dev
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.java_distribution }}
          java-version: ${{ env.java_version }}
          cache: ${{ env.java_cache }}
      - run: ./gradlew build
        working-directory: ${{ env.working_directory }}
      - run: ./gradlew test
        working-directory: ${{ env.working_directory }}